[2024-07-14T04:36:31.761+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:36:31.770+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [queued]>
[2024-07-14T04:36:31.774+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [queued]>
[2024-07-14T04:36:31.774+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-14T04:36:31.778+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_task> on 2024-07-14 04:31:29.834169+00:00
[2024-07-14T04:36:31.781+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8286) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T04:36:31.782+0000] {standard_task_runner.py:63} INFO - Started process 8287 to run task
[2024-07-14T04:36:31.782+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train', 'train_task', 'manual__2024-07-14T04:31:29.834169+00:00', '--job-id', '32', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpk9fynr8f']
[2024-07-14T04:36:31.782+0000] {standard_task_runner.py:91} INFO - Job 32: Subtask train_task
[2024-07-14T04:36:31.798+0000] {task_command.py:426} INFO - Running <TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [running]> on host afe03d974b6e
[2024-07-14T04:36:31.823+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train' AIRFLOW_CTX_TASK_ID='train_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T04:31:29.834169+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T04:31:29.834169+00:00'
[2024-07-14T04:36:31.823+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:36:32.021+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:36:32.022+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/train.py", line 4, in train
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
[2024-07-14T04:36:32.026+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=train, task_id=train_task, run_id=manual__2024-07-14T04:31:29.834169+00:00, execution_date=20240714T043129, start_date=20240714T043631, end_date=20240714T043632
[2024-07-14T04:36:32.030+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 32 for task train_task (No module named 'plotly'; 8287)
[2024-07-14T04:36:32.046+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T04:36:32.054+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:36:32.054+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
