[2024-07-14T04:31:30.569+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-14T04:31:30.577+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [queued]>
[2024-07-14T04:31:30.579+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [queued]>
[2024-07-14T04:31:30.579+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-07-14T04:31:30.583+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): train_task> on 2024-07-14 04:31:29.834169+00:00
[2024-07-14T04:31:30.585+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=8213) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-14T04:31:30.586+0000] {standard_task_runner.py:63} INFO - Started process 8214 to run task
[2024-07-14T04:31:30.586+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'train', 'train_task', 'manual__2024-07-14T04:31:29.834169+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/train_dag.py', '--cfg-path', '/tmp/tmpi3j45t9p']
[2024-07-14T04:31:30.586+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask train_task
[2024-07-14T04:31:30.601+0000] {task_command.py:426} INFO - Running <TaskInstance: train.train_task manual__2024-07-14T04:31:29.834169+00:00 [running]> on host afe03d974b6e
[2024-07-14T04:31:30.623+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train' AIRFLOW_CTX_TASK_ID='train_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-14T04:31:29.834169+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-14T04:31:29.834169+00:00'
[2024-07-14T04:31:30.624+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-14T04:31:30.801+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-14T04:31:30.802+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/tasks/train.py", line 4, in train
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'
[2024-07-14T04:31:30.805+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=train, task_id=train_task, run_id=manual__2024-07-14T04:31:29.834169+00:00, execution_date=20240714T043129, start_date=20240714T043130, end_date=20240714T043130
[2024-07-14T04:31:30.809+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 31 for task train_task (No module named 'plotly'; 8214)
[2024-07-14T04:31:30.853+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-14T04:31:30.861+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-14T04:31:30.862+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
